__title__ = 'Django Simplify'
__package_name__ = 'django-simplify'
__author__ = 'Taiwo Kareem'
__description__ = ' '.join('''Provides Ruby on Rails-like command line functionalities, models and helper functions so you can focus on development and removes the pain of repeating frequent actions.'''.strip().split())
__email__ = 'taiwo.kareem36@gmail.com'
__version__ = '0.1.2'
__license__ = 'BSD'
__copyright__ = 'Copyright 2021 Taiwo Kareem'
__url__ = 'https://github.com/tushortz/django-simplify'
__keywords__="django, model helpers, django commands, helpers"
